/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';

// VERSION CONTROL - Increment on each deployment
const CACHE_VERSION = 'v1.1.4';

clientsClaim();

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// SPA shell routing
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache PNG images
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  new StaleWhileRevalidate({
    cacheName: `images-${CACHE_VERSION}`,
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  })
);

// Cache other image formats
registerRoute(
  ({ url }) => url.origin === self.location.origin && /\.(jpg|jpeg|gif|svg|webp)$/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: `images-${CACHE_VERSION}`,
    plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  })
);

// Cache CSS and JS
registerRoute(
  ({ url }) => url.origin === self.location.origin && /\.(css|js)$/.test(url.pathname),
  new NetworkFirst({
    cacheName: `static-resources-${CACHE_VERSION}`,
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  })
);

// Cache Google Fonts
registerRoute(
  ({ url }) =>
    url.origin === 'https://fonts.googleapis.com' ||
    url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: `google-fonts-${CACHE_VERSION}`,
    plugins: [new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 365 * 24 * 60 * 60 })],
  })
);

// ─── Skip Waiting ─────────────────────────────────────────────────────────────
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    console.log('⏭️ Skipping waiting phase...');
    self.skipWaiting();
  }
});

// ─── Activate: clean up old caches ───────────────────────────────────────────
self.addEventListener('activate', (event) => {
  console.log(`🔄 Service Worker ${CACHE_VERSION} activating...`);
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames.map((cacheName) => {
          if (
            !cacheName.includes(CACHE_VERSION) &&
            (cacheName.startsWith('images-') ||
              cacheName.startsWith('static-resources-') ||
              cacheName.startsWith('google-fonts-'))
          ) {
            console.log('🗑️ Deleting old cache:', cacheName);
            return caches.delete(cacheName);
          }
        })
      )
    ).then(() => {
      console.log('✅ Service Worker activated, old caches cleaned');
      return self.clients.claim();
    })
  );
});

console.log(`🚀 EcoSort Service Worker ${CACHE_VERSION} loaded`);