/* eslint-disable no-restricted-globals */
/* global firebase, importScripts, clients */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';

importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-messaging-compat.js');

const firebaseConfig = {
  apiKey: "AIzaSyDWRvunKHCqs3maebTRr1dICfxb04XGW6A",
  authDomain: "ecosort-51471.firebaseapp.com",
  projectId: "ecosort-51471",
  storageBucket: "ecosort-51471.appspot.com",
  messagingSenderId: "296718734304",
  appId: "1:296718734304:web:852095c72930c6b61a1185",
  measurementId: "G-31NRJCYK8P",
};

// Initialize Firebase only if it hasn't been initialized yet
if (typeof firebase !== 'undefined' && firebase.apps.length === 0) {
  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    console.log('[service-worker.js] Received background message ', payload);
    
    // The logic to display the OS notification
    const notificationTitle = payload.notification.title || 'New EcoSort Update';
    const notificationOptions = {
      body: payload.notification.body,
      icon: '/logo192.png',
      badge: '/favicon.ico', 
      data: payload.data, 
      requireInteraction: true, 
      actions: [
        {action: 'open', title: 'Open App'}
      ]
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
  });
  
  // CRITICAL LOG: Confirm listener is active
  console.log('✅ FCM Background Listener Initialized in Service Worker');

} else {
  console.log('⚠️ Firebase was already initialized in this Service Worker scope.');
}

// VERSION CONTROL - Increment on each deployment
const CACHE_VERSION = 'v1.1.31'; 

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') {
      return false;
    }
    if (url.pathname.startsWith('/_')) {
      return false;
    }
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache images
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  new StaleWhileRevalidate({
    cacheName: `images-${CACHE_VERSION}`,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

registerRoute(
  ({ url }) => url.origin === self.location.origin && /\.(jpg|jpeg|gif|svg|webp)$/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: `images-${CACHE_VERSION}`,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 30 * 24 * 60 * 60 }), // 30 days
    ],
  })
);

// Cache CSS and JS files
registerRoute(
  ({ url }) => url.origin === self.location.origin && /\.(css|js)$/.test(url.pathname),
  new NetworkFirst({
    cacheName: `static-resources-${CACHE_VERSION}`,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: `google-fonts-${CACHE_VERSION}`,
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 365 * 24 * 60 * 60 }),
    ],
  })
);


// Handle Skip Waiting
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    console.log('⏭️ Skipping waiting phase...');
    self.skipWaiting();
  }
});

// Clean up old caches
self.addEventListener('activate', (event) => {
  console.log(`🔄 Service Worker ${CACHE_VERSION} activating...`);
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (!cacheName.includes(CACHE_VERSION) && 
              (cacheName.startsWith('images-') || 
               cacheName.startsWith('static-resources-') || 
               cacheName.startsWith('google-fonts-'))) {
            console.log('🗑️ Deleting old cache:', cacheName);
            return caches.delete(cacheName);
          }
        })
      );
    }).then(() => {
      console.log('✅ Service Worker activated and old caches cleaned');
      return self.clients.claim();
    })
  );
});

self.addEventListener('install', (event) => {
  console.log(`📦 Service Worker ${CACHE_VERSION} installing...`);
  self.skipWaiting();
});

// Optional: Handle Notification Clicks (Open app when notification clicked)
self.addEventListener('notificationclick', function(event) {
  console.log('[Service Worker] Notification click received.');
  
  event.notification.close();

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
      // If there is already a window open, focus it
      if (clientList.length > 0) {
        let client = clientList[0];
        for (let i = 0; i < clientList.length; i++) {
          if (clientList[i].focused) {
            client = clientList[i];
          }
        }
        
        // Use custom data to decide where to go
        const targetPage = event.notification.data?.target_page || '/';
        
        // If the client is the same origin, navigate to the target page
        if (client.url.startsWith(self.location.origin)) {
            client.navigate(targetPage);
        }
        return client.focus();
      }
      // Otherwise open a new window
      return clients.openWindow('/');
    })
  );
});

console.log(`🚀 EcoSort Service Worker ${CACHE_VERSION} loaded`);